### ISSUE TITLE
Path to procfs is not configurable

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap-plugin-collector-cpu#14]
The path to procfs is currently [hardcoded](https://github.com/intelsdi-x/snap-plugin-collector-cpu/blob/master/cpu/cpu.go#L115) to `/proc`. This makes it hard (if even possible) to use the plugin when snapd is run in a Docker container.

Note: with the psutil plugin, which relies on the [gopsutil library](https://github.com/shirou/gopsutil), the path to procfs can be configured through the `HOST_PROC` envvar. The Snap plugins should make the path to procfs configurable in a consistent manner (probably through a plugin config parameter in the task/workflow definition).

**Comment by mjbrender** [comment]
Great feedback @elemoine - thank you for opening this one. Given the use case, let's keep this in mind on the next rev of this plugin. cc @intelsdi-x/plugin-maintainers

**Comment by lynxbat** [comment]
I believe this needs to be tracked as a bug @mjbrender @bjray

**Comment by mjbrender** [comment]
@lynxbat agreed!
