### ISSUE TITLE
Plugin repository should be tagged whenever binary releases are produced

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap-plugin-collector-cpu#23]
Looking at issue #20 it is hard to figure out if this issue is a duplicate of #18.
Tagging/branching of plugin repository could really ease up support investigations

**Comment by katarzyna-z** [comment]
@obourdon Could you provide more information about your idea? Now, we have the plugin version which is increased when significant change is introduced, in [this](https://github.com/intelsdi-x/snap-plugin-collector-cpu/blob/master/cpu/cpu.go#L51) line there is a variable which should be increased. You can see the plugin version using snapctl, e.g: 

```
$ snapctl plugin list
NAME 		 VERSION 	 TYPE 		 SIGNED 	 STATUS 	 LOADED TIME
postgresql 	 9 		 publisher 	 false 		 loaded 	 Wed, 31 Aug 2016 14:19:50 CEST
load 		 3 		 collector 	 false 		 loaded 	 Wed, 31 Aug 2016 14:20:29 CEST
mock 		 1 		 collector 	 false 		 loaded 	 Wed, 31 Aug 2016 14:19:26 CEST
mock 		 2 		 collector 	 false 		 loaded 	 Wed, 31 Aug 2016 14:19:26 CEST
passthru 	 1 		 processor 	 false 		 loaded 	 Wed, 31 Aug 2016 14:19:27 CEST
mock-file 	 3 		 publisher 	 false 		 loaded 	 Wed, 31 Aug 2016 14:19:27 CEST
``` 
Do you think that additional tagging is needed?

**Comment by nanliu** [comment]
We improved our release process and generate new plugins whenever we have a new git tag. Moving forward, any new code should result in a new tag/release. Let us know if this addresses your concern.

**Comment by nanliu** [comment]
If you have any concerns that haven't been addressed, please feel free to reopen this issue.
