### ISSUE TITLE
getStats called during init

### ISSUE THREAD

**Issue by marcin-krolik** [intelsdi-x/snap-plugin-collector-cpu#25]
Inside `p.init` apart from reading configuration, there is a [call](https://github.com/obourdon/snap-plugin-collector-cpu/blob/e59905586ee357391e1eecab6f7e1f0178038b50/cpu/cpu.go#L226) to `getStats`. `p.init` should not call `getStats`, it should only initialize state of the plugin, so later on `getStats` can be called safely.

I suggest to remove `getStats` from `p.init`, and then above block can be rewritten to

```go
if !p.initialized {
	if err := p.init(metricTypes[0].Config().Table()); err != nil {
		return nil, err
	}
}

if err := getStats(p.stats, p.prevMetricsSum, p.cpuMetricsNumber, p.snapMetricsNames, p.procStatMetricsNames); err != nil {
	return nil, err
 }
```

**Comment by obourdon** [comment]
New version submitted

**Comment by obourdon** [comment]
Fixed by [this commit](https://github.com/intelsdi-x/snap-plugin-collector-cpu/pull/22/commits/0fc9ff0bb2fb90fdcfc19123e26ee868ad156eb7)
