### ISSUE TITLE
Error loading plugin:

### ISSUE THREAD

**Issue by ramakrishnan42** [intelsdi-x/snap-plugin-collector-cpu#26]
when i try to load the snap-plugin-collector-cpu plugin, it shows this error.
Error loading plugin:
gob: type mismatch: no fields matched compiling decoder for GetMetricTypesReply

help me.

**Comment by katarzyna-z** [comment]
@ramakrishnan42 I tested the latest version of cpu plugin ([commit](https://github.com/intelsdi-x/snap-plugin-collector-cpu/commit/b07606035d0c2a819f9792d131f7e3ca2ded1448)) with the latest version of snap ([commit](https://github.com/intelsdi-x/snap/commit/ed1733bfe09156af557fafc972b7a5a9de8a0867)) and it is working without errors. Could you check the latest versions of the plugin ans snap in your working environment?

**Comment by ramakrishnan42** [comment]
@katarzyna-z  Thank U. I updated the latest version.now its is working.
