### ISSUE TITLE
Support linux distros with less than 10 columns for CPU in /proc/stat

### ISSUE THREAD

**Issue by jtlisi** [intelsdi-x/snap-plugin-collector-cpu#27]
When I try to run this plugin on my linux distro it fails because the /proc/stat cpu line does not have an adequate number of columns. 

`$ snapctl plugin load plugin/snap-plugin-collector-cpu`
`   Error loading plugin:`
`   GetMetricTypes call error : Wrong data length. Expected {10} is {9}`

I was thinking of altering the plugin to be column agnostic so it will return metrics for a stat file regardless what version of the kernel is being run.

**Comment by obourdon** [comment]
According to https://www.kernel.org/doc/Documentation/filesystems/proc.txt section 1.8 the number of columns in /proc/stat is fixed and in the contrary of /proc/mountinfo it can not vary

Which flavour of Linux are you running on ? Which version or kernel ? Can you post your current /proc/stat output please ?

**Comment by jtlisi** [comment]
I'm dealing with some kernels that are pre 2.6.33 so there only have 9 columns for cpu procs. I also wouldn't be surprised if I have to support some pre 2.6.24 kernels which means only 8 columns. Here is the proc/stat output from a linux 2.6.32 kernel on Red Hat OS.

`cpu  180401494 227200 18747745 3823269793 1561918 12082 2511349 0 0`
`cpu0 22541572 28113 2329501 477843628 173611 1735 315175 0 0`
`cpu1 23343161 22869 2630545 476714355 160618 1759 329698 0 0`
`cpu2 23273074 23301 2379599 477185773 228802 1313 306784 0 0`
`cpu3 21737146 25142 2469295 478517759 182886 1368 292683 0 0`
`cpu4 23632020 23371 2328432 476806713 149935 1518 299584 0 0`
`cpu5 16482157 57919 1670304 485297613 261028 879 192659 0 0`
`cpu6 20697156 27340 2003275 480427194 266605 852 250781 0 0`
`cpu7 28695204 19141 2936792 470476756 138429 2654 523982 0 0`

As you can see, only nine columns. I edited the plugin to just append a "0" for the missing 10th metric Guest_Nice as a quick fix. However, I am interested in submitting a pull request to alter the plugin to accommodate older kernels.

**Comment by marcin-krolik** [comment]
@jtlisi Thanks for your input! You are more then welcome to open PR. I can help if you have any problems, or opened questions. Just shoot!

**Comment by IzabellaRaulin** [comment]
Resolved by #29
