### ISSUE TITLE
snaptel task watch - cause high CPU

### ISSUE THREAD

**Issue by discoduck2x** [intelsdi-x/snap-plugin-collector-cpu#50]
**Snap daemon version** (use `snapteld -v`): 1.1.0

**Environment**:
- **Cloud provider or hardware configuration**: vmware
- **OS** (e.g. from /etc/os-release): red hat
- **Kernel** (e.g. `uname -a`):  3.10.0-327.36.2.el7.x86_64
- **Relevant tools** (e.g. plugins used with Snap): snap-plugin-collector-cpu , snap-plugin-publisher-influxdb_linux_x86_64

**What happened**:

creating task to just check cpu cores utilization % , then via cli "watch" the task, this cause snaptel process to consume 100% cpu and stop updating task watch data until ctrl-c

**What you expected to happen**:
..not getting a cpu util issue

task config .json :
```
{
  "version": 1,
  "schedule": {
    "type": "simple",
    "interval": "1s"
  },
  "max-failures": -1,
  "workflow": {
    "collect": {
      "metrics": {
        "/intel/procfs/cpu/*/system_percentage": {},
        "/intel/procfs/cpu/*/user_percentage": {}
      },
      "config": {
        "/intel/procfs/cpu": {
          "proc_path": "/proc"
        }
      },
      "publish": [
        {
          "plugin_name": "influxdb",
          "config": {
            "host": "x.x.x.x",
            "port": 8086,
            "database": "snap",
            "user": "admin",
            "password": "admin",
            "scheme": "http",
            "skip-verify": false,
            "isMultiFields": true
          }
        }
      ]
    }
  }
}
```

starting to watch task,,, after ~10seconds the update cli stops..

![image](https://cloud.githubusercontent.com/assets/12600004/22886567/c1e11fd2-f1fe-11e6-906b-afb442c7b04b.png)

...and the snaptel process eats cpu

![image](https://cloud.githubusercontent.com/assets/12600004/22886593/e54166da-f1fe-11e6-97eb-b68b3b82bea9.png)

...still inserts into influx

![image](https://cloud.githubusercontent.com/assets/12600004/22886632/ff807cd4-f1fe-11e6-901b-bc291d45472b.png)

**Comment by mkleina** [comment]
I was able to reproduce this issue, both on version 1.1.0 and latest master-85079bc. Also checked some other plugins (snap-plugin-collector-smart, snap-plugin-collector-perfevents) and that the same issue exists, so it seems that it is recent Snap CLI issue. I will create issue on Snap repo.
